### ISSUE TITLE
Test if syncing with > 2M files through syncthing works

### ISSUE THREAD

**Issue by FastGeert** [zero-os/autotests#2]
Using syncting to synchronize the data between multiple minio heads could be a viable alternative for making a minio deployment redundant. It would also be more cost effective, as we'll need less memory for the vm's running the minio compared with the mongodb solution.

Test setup:
- Start two zero-os vms with database disk on two phisical machines using a shared private network (vxlan)
- Create a filesystem on the database disk
- Create container in each vm, with /var mounted on the filesystem created in the previous step and hostnetworking
- In the container run two programs:
  - Syncthing to sync /var contents with the container on the other zero-os vm
  - A program (python script) that generates random files of about 10kb each, every second

Success criteria:
- Files created should be synced to the other side within < 5 seconds

**Comment by arahmanhamdy** [comment]
Have tested the sync between two minio servers on separate laptops with syncthing and ran a script that creates 60 files/min with 10kb each

The results varies according to the network speed as the difference btween finishing the creation of files and syncing was:
2.5 seconds - 11, 1 seconds

Script used for testing: 
```python
import time
import os
from minio import Minio

files_count = 60
file_size_kb = 10
path = "/home/abdulrahman/Sync/test"

localClient = Minio('localhost:9000',
                    access_key='',
                    secret_key='',
                    secure=False)
remoteClient = Minio('197.162.249.37:9000',
                     access_key='',
                     secret_key='',
                     secure=False)

# Empty the local bucket
objects = localClient.list_objects('test', recursive=True)
object_names = [my_object.object_name for my_object in objects]
for del_err in localClient.remove_objects('test', object_names):
    print("Deletion Error: {}".format(del_err))

# Empty the remote bucket
objects = remoteClient.list_objects('test', recursive=True)
object_names = [my_object.object_name for my_object in objects]
for del_err in remoteClient.remove_objects('test', object_names):
    print("Deletion Error: {}".format(del_err))

start_time = time.time()
for i in range(files_count):
    with open("%s/random%s" % (path, i), "wb") as out:
        out.write(os.urandom(1024 * file_size_kb))
    time.sleep(1)
end_time = time.time()
process_time = end_time - start_time

print("Start Time: ", start_time)
print("End Time: ", end_time)
print("Process Time: ", process_time)

objects = []
while True:
    objects = remoteClient.list_objects('test', recursive=True)
    synced = len(list(objects))
    if synced == files_count:
        break

print("Sync Time Difference:", time.time() - end_time)
```

**Comment by hossnys** [comment]
Now i just tested syncing between two vms running on two nodes on Bancadati farm and the speed of syncing was magnificent as 1GB file take 38 sec to be created and synced ,, will modify the script later to check for syncing many small files over 2 vms .

**Comment by hossnys** [comment]
the script modified to get the sync time between two vms not minios but all Bancadati nodes are shutdown for now

**Comment by zaibon** [comment]
can we run this test with a huge number of files ? 10k 1M ?

**Comment by hossnys** [comment]
i repeated test again with10.000 files using threads in script and over two vms connected over Zt netwok and the sync time was 96 seconds.
here is the script :
[test_sync_with_threads.txt](https://github.com/zero-os/autotests/files/2246215/test_sync_with_threads.txt)

**Comment by zaibon** [comment]
ok that's wat I thought, so this is for sure not going to scale.

**Comment by rkhamis** [comment]
What I understood was that the entire testing time.
@hossnys what was the latency and throughput?
How long did it take for each file to by synced? Did any exceed 5 seconds?

**Comment by hossnys** [comment]
now the last scenarios tested ::
1- creating 60 files 10 KB for each  using threads , and sync time for all process take 3.053 seconds .
2- creating 60 file 10 KB for each , 1 per second . and the last file only  sync time was 0.3 second.
3- dropping folder with 60 files 10 KB for each in the sync directory , the sync time was 1.1 sec.

from the results , i found that the sync process time depends on how many modification actions is happening on the file to be synced, as long as modification is happening  the sync process will still in action
