### ISSUE TITLE
Test S3 with 2 minio vms and syncting to synchronize metadata

### ISSUE THREAD

**Issue by FastGeert** [zero-os/autotests#4]
This is an extension on https://github.com/zero-os/autotests/issues/3

The goal is to load test a setup without MongoDB and see if the system will cope. Don't forget to configure the caddy reverse proxy in the 0-GW to load balance the S3 api over the two minio's

Test with small and large files from different clients.

Use things like restic, but also other ways to push data on the system.

Make sure to also read, and validate the integrity of the data.

**Comment by rkhamis** [comment]
@ramezsaeed please see setup documented by @grimpy in #3

**Comment by grimpy** [comment]
These are the toml configs you can use for zero-os (protocol) extract in your configmanager

Current setup is using the first 6 nodes from rack F10
```
node1 = j.clients.zos.sal.get_node('MAN-DC01-F1001-ARC01')
node1 = j.clients.zos.sal.get_node('MAN-DC01-F1001-ARC01')
node2 = j.clients.zos.sal.get_node('MAN-DC01-F1005-ARC02')
node3 = j.clients.zos.sal.get_node('MAN-DC01-F1009-ARC03')
node4 = j.clients.zos.sal.get_node('MAN-DC01-F1013-ARC04')
node5 = j.clients.zos.sal.get_node('MAN-DC01-F1017-ARC05')
node6 = j.clients.zos.sal.get_node('MAN-DC01-F1021-ARC06')
```
Yes this is old format of getting the client

node1 and node2 have both 2 zdbs exposed on their primary iunterace (backplane)
```
zdbs = ['10.10.100.131:9910', '10.10.100.131:9911', '10.10.100.132:9910', '10.10.100.132:9911']  
```
node3 was giving me some network issues (duplicate IP somewhere)

node4 has zgw running with default networking mode (not public interface available at the time this was setup)

node5 has the minio vm setup its redis port is exposed via the zgw is also a has a ubuntu vm which was used for troubleshooting (config included under miniozos)
[bancadati.tar.gz](https://github.com/zero-os/autotests/files/2286006/bancadati.tar.gz)


node6 has a container which was used for test

**Comment by ramezsaeed** [comment]
not needed anymore
